export function NewName() {
    let name = Names[Math.floor(Math.random() * Names.length)];
    let verb = Verbs[Math.floor(Math.random() * Verbs.length)];

    return `${verb} ${name}`;
}

const Names = [
    'Aardvark',
    'Alligator',
    'Alpaca',
    'Anteater',
    'Antelope',
    'Ape',
    'Armadillo',
    'Baboon',
    'Badger',
    'Bandicoot',
    'Bat',
    'Beaver',
    'Billy Goat',
    'Bird',
    'Bison',
    'Bear',
    'Boar',
    'Bob-Cat',
    'Bonobo',
    'Buffalo',
    'Camel',
    'Capybara',
    'Caribou',
    'Cat',
    'Cheetah',
    'Chimpanzee',
    'Chinchilla',
    'Chipmunk',
    'Cougar',
    'Cow',
    'Coyote',
    'Crocodile',
    'Deer',
    'Degus',
    'Dingo',
    'Dog',
    'Dolphin',
    'Donkey',
    'Dormouse',
    'Platypus',
    'Elephant',
    'Elk',
    'Ermine',
    'Ferret',
    'Fish',
    'Fox',
    'Frog',
    'Gazelle',
    'Gecko',
    'Anteater',
    'Gibbon',
    'Giraffe',
    'Goat',
    'Gopher',
    'Gorilla',
    'Grizzly',
    'Groundhog',
    'Hare',
    'Hedgehog',
    'Hippopotamus',
    'Horse',
    'Hyena',
    'Iguana',
    'Impala',
    'Jackal',
    'Jackrabbit',
    'Jaguar',
    'Jellyfish',
    'Kangaroo',
    'Koala',
    'Komodo',
    'Kookaburra',
    'Lama',
    'Lamb',
    'Lemming',
    'Lemur',
    'Leopard',
    'Lion',
    'Llama',
    'Lynx',
    'Manatee',
    'Manta Ray',
    'Mantis',
    'Marmot',
    'Meerkat',
    'Mink',
    'Mole',
    'Mollusk',
    'Mongoose',
    'Monk Seal',
    'Monkey',
    'Moose',
    'Mountain Lion',
    'Mouse',
    'Mule',
    'Muskox',
    'Muskrat',
    'Narwhal',
    'Nautilus',
    'Newt',
    'Octopus',
    'Orangutan',
    'Orca',
    'Otter',
    'Ox',
    'Panda',
    'Panther',
    'Pig',
    'Platypus',
    'Polar Bear',
    'Porcupine',
    'Porpoise',
    'Possum',
    'Potbellied Pig',
    'Potto',
    'Puma',
    'Rabbit',
    'Raccoon',
    'Rat',
    'Ray',
    'Reindeer',
    'Rhino',
    'Rhinoceros',
    'Salamander',
    'Sea Lion',
    'Seal',
    'Shark',
    'Skunk',
    'Sloth',
    'Snake',
    'Snow Fox',
    'Snow Hare',
    'Snow Leopard',
    'Sperm Whale',
    'Spotted Dolphin',
    'Squirrel',
    'Sea Lion',
    'Terrapin',
    'Tiger',
    'Tortoise',
    'Tree Frog',
    'Turtle',
    'Vampire Bat',
    'Monkey',
    'Vole',
    'Wallaby',
    'Walrus',
    'Warthog',
    'Water Buffalo',
    'Weasel',
    'Whale Shark',
    'Whale',
    'Rhino',
    'Wildcat',
    'Wildebeest',
    'Shark',
    'Wolf',
    'Wombat',
    'Woodchuck',
    'Yak',
    'Marmot',
    'Zebra',
    'Zebu',
    'Zorilla'
];

const Verbs = [
    'Amber',
    'Amethyst',
    'Apricot',
    'Aquamarine',
    'Azure',
    'Baby blue',
    'Brick red',
    'Black',
    'Blue',
    'Blue-green',
    'Blue-violet',
    'Blush',
    'Bronze',
    'Burgundy',
    'Byzantium',
    'Carmine',
    'Cerise',
    'Champagne',
    'Chocolate',
    'Cobalt blue',
    'Coffee',
    'Copper',
    'Coral',
    'Crimson',
    'Cyan',
    'Emerald',
    'Gold',
    'Green',
    'Harlequin',
    'Indigo',
    'Ivory',
    'Jade',
    'Lavender',
    'Lemon',
    'Lilac',
    'Lime',
    'Magenta',
    'Maroon',
    'Navy blue',
    'Ochre',
    'Olive',
    'Orange',
    'Orchid',
    'Peach',
    'Pink',
    'Plum',
    'Purple',
    'Raspberry',
    'Red',
    'Red-violet',
    'Ruby',
    'Sapphire',
    'Silver',
    'Tan',
    'Teal',
    'Turquoise',
    'Ultramarine',
    'Violet',
    'Viridian',
    'White',
    'Yellow'
];